//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netwolf.Generator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Diagnostics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Diagnostics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Netwolf.Generator.Resources.Diagnostics", typeof(Diagnostics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A CommandAttribute may only be placed on a method in a class that inherits from Netwolf.BotFramework.Bot.
        /// </summary>
        internal static string InvalidCommandContextMessageFormat {
            get {
                return ResourceManager.GetString("InvalidCommandContextMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CommandAttribute location.
        /// </summary>
        internal static string InvalidCommandContextTitle {
            get {
                return ResourceManager.GetString("InvalidCommandContextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command name &apos;{0}&apos; is invalid; it must be a non-empty string containing only ASCII letters and digits.
        /// </summary>
        internal static string InvalidCommandNameMessageFormat {
            get {
                return ResourceManager.GetString("InvalidCommandNameMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command name.
        /// </summary>
        internal static string InvalidCommandNameTitle {
            get {
                return ResourceManager.GetString("InvalidCommandNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default value for parameter &apos;{0}&apos; is not supported by Netwolf.PluginFramework. Please report this issue to the Netwolf developers..
        /// </summary>
        internal static string UnsupportedParameterDefaultMessageFormat {
            get {
                return ResourceManager.GetString("UnsupportedParameterDefaultMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported command parameter default value.
        /// </summary>
        internal static string UnsupportedParameterDefaultTitle {
            get {
                return ResourceManager.GetString("UnsupportedParameterDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter type &apos;{0}&apos; for parameter &apos;{1}&apos; is not supported for command handlers. The type must be convertible from string either via TypeConverterAttribute, an explicit or implicit user-defined conversion operator, or a public constructor that takes string as its only parameter..
        /// </summary>
        internal static string UnsupportedParameterTypeMessageFormat {
            get {
                return ResourceManager.GetString("UnsupportedParameterTypeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported command parameter type.
        /// </summary>
        internal static string UnsupportedParameterTypeTitle {
            get {
                return ResourceManager.GetString("UnsupportedParameterTypeTitle", resourceCulture);
            }
        }
    }
}
